src/metadata.rs
src/query/query.pest
src/query/query_eval.rs
src/query/query_parse.rs
src/query/query_types.rs
tests/test_api.rs
tests/test_query.rs

Note this will only work for string types at the moment, will add querying for numeric types in a separate PR.
But after this PR you can now run a query like
```
parameter:disease == "YF"
```
or 
```
latest(parameter:iso3 == "MWI")
```

mrc-4335: Add parameters search into outpack rust querying

---

src/metadata.rs
src/query/query.pest
src/query/query_eval.rs
src/query/query_parse.rs
src/query/query_types.rs
tests/test_api.rs
tests/test_query.rs

Reverts mrc-ide/outpack_server#15
This is causing errors when we try to deserialise a packet with an integer parameter. So let's revert for now. We then need to iterate on this PR so that either it deserialises into the specific type (must support int, float, bool and string) or cast them all to string. If the later - check the behaviour in R querying. R can search for `parameter:x == 0.15` or `parameter:x == "0.15"` as equivalent. Does this work for boolean too?

Revert "mrc-4335: Add parameters search into outpack rust querying"

---

src/index.rs
src/location.rs
src/metadata.rs
src/query/query_format.rs
tests/example/.outpack/location/ae7a7bcb/20180220-095832-16a4bbed
tests/example/.outpack/metadata/20180220-095832-16a4bbed
tests/test_api.rs

This PR will
* Add a new packet into the example which has 4 parameters, 1 float, 1 int, 1 string and 1 bool
* Will deserailise these into an `Option<HashMap<String, serde_json::Value>>`
* Add a method `parameter_equals` which can be used for testing if a `Packet` has a parameter with a certain value (see #21 for an example of how I want to use this)
I want to use this to fix up #15 which we had to revert because the changes I made there were causing issues with deserialisation. See #18

Deserialize packet parameters and add helper function to test equality

---

buildkite/docker
src/location.rs
src/metadata.rs
tests/example/.outpack/unpacked/20170818-164830-33e0ab01
tests/test_api.rs

This PR removes the `.outpack/unpacked` directory from the example, and updates the limited code that uses it to no longer need it.
See https://github.com/mrc-ide/outpack/pull/76 for context, this is where it was removed from outpack.

Remove the unpacked directory

---

README.md
schema/list.json
schema/location.json
src/api.rs
src/hash.rs
src/location.rs
src/metadata.rs
src/store.rs
src/test_utils.rs
src/utils.rs
tests/test_api.rs

Adds `POST /packet<hash>` which should replicate the logic of:
```
location_path_import_metadata <- function(str, hash, root) {
meta <- outpack_metadata_load(as_json(str))
id <- meta$id
hash_validate_data(str, hash, sprintf("metadata for '%s'", id))
unknown_files <- root_list_unknown_files(meta$files$hash, root)
if (length(unknown_files) > 0) {
stop(
sprintf("Can't import metadata for '%s', as files missing:\n%s",
id, paste(sprintf("  - %s", unknown_files), collapse = "\n")))
}
unknown_packets <- root_list_unknown_packets(meta$depends$packet, TRUE, root)
if (length(unknown_packets) > 0) {
stop(sprintf(
"Can't import metadata for '%s', as dependencies missing:\n%s",
id, paste(sprintf("  - %s", unknown_packets), collapse = "\n")))
}
if (!is.null(root$config$core$path_archive)) {
dst <- …
```

mrc-4310 POST metadata endpoint

---

schema/config.json
src/config.rs
src/location.rs
tests/bad-example/.outpack/config.json
tests/example/.outpack/config.json

Pairs with an orderly2 PR (https://github.com/mrc-ide/orderly2/pull/57), but this one should be merged first.
Walking back the "priority" idea for locations, it was not actually useful and not referenced anywhere yet, so just removing it. It looks like the ordering returned from disk is arbitrary or locale/platform dependent so I've ordered based on how they appear in the config which makes the tests stable (it is what orderly2 does too, but it also does not matter)

Drop priority from locations

---

src/store.rs

Backing out of the approach used in: 70c0403 ([files](https://github.com/mrc-ide/outpack_server/tree/70c0403141851181f295a429ae9ac08d4174f3ed))
> This PR uses a temporary location in the same directory as the hash itself, guaranteeing that the rename is possible due to not crossing filesystem boundary.
Now we just do copy_to rather than persist_to, which will work in a docker context

Use temporary file location in same fs

---

src/api.rs
src/bin/outpack_server.rs
src/config.rs
tests/test_api.rs

* moves the existing Root class into the api as it's not really the outpack root, but the serde template for json serialisation.
* validates that the outpack config has suitable values for use with the server
~Merge after #30, contains those commits~

Tidy up api start

---

Dockerfile
src/bin/outpack_init.rs
src/config.rs
src/init.rs
src/lib.rs

This stretches our cli framework to the limit, it's getting a bit junky now, but the clap refactor can happen later.
This PR does a basic initialisation of an outpack root from the rust cli. This will simplify the deployment as we won't need another container, we can just use the server one we have - we might also update the api to create the directory as it starts, perhaps as an option.
Possible improvements would include indicating which configuration options have changed rather than just bailing.
Pretty pleased to have been able to do this with minimal googling now, stuck on a train crawling out of london...

mrc-4558: Create an outpack root from the cli

---

src/metadata.rs
src/query/query.pest
src/query/query_eval.rs
src/query/query_parse.rs
src/query/query_types.rs
src/query/test_utils_query.rs
tests/test_query.rs

This builds on #37 and should be merged after that
This PR just replaces strings like `"parameter:x == \"thing\""` with `r#"parameter:x == "thing""#`

Use raw strings instead of escaping quotes

---

src/metadata.rs
src/query/query.pest
src/query/query_eval.rs
src/query/query_parse.rs
src/query/query_types.rs
src/query/test_utils_query.rs
tests/test_query.rs

This was a little bit of a fiddly one and there is some churn here but I think the end result isn't too bad actually!
This PR will add support to the querying language to run use additional tests `!=`, `<`, `>`, `<=`, `>=`. With this PR you should be able to run queries like
* `id != "123"`
* `name != "my_report"`
* `parameter:x > 2`
* `parameter:x >= 0.002`
* `parameter:y < 5`
* `parameter:y <= 5`
If you use a bool or a string on any of the ordering queries `<`, `<=`, `>`, `>=` this will return return no matches. We don't do any type coersion. This agrees with current verison in the R impl.

mrc-4549: Add support for other comparison operators

---

src/query/query.pest
src/query/query_eval.rs
src/query/query_parse.rs
src/query/query_types.rs
tests/test_query.rs

This PR will add support into the querying for the `single` function which asserts that the inner query contains one and only one packet.

mrc-4551: Add function to assert only a single packet returned from query

---

src/query/mod.rs
src/query/query.pest
src/query/query_parse.rs

The query language allows for a few short-form syntaxes that are only valid at the toplevel, not within complex expressions. Previously these were handled through a "preparse" step that would match on the string with regexes and convert it into a valid expression.
This commit replaces the preparsing step with a few new rules in the PEG-based parser. This makes the parser more consistent and should allow for better errorsi by keeping the spans accurate.
This also solves an inconvenience of the parser API. The nodes generated by the parser borrow from its input string, and are therefore bound by that lifetime. Previously that "input string" was actually the preprocessed query, rather than the original query. The output nodes would therefore have to borrow from that temporary string which …

Remove the need for a preparsing step.

---

.github/workflows/build-test.yaml
src/store.rs

`put_file` (and its unit tests) was using the hash, including the hash type with its colon separator, as part of a temporary filename. This is not supported on Windows. The actual temporary file name does not matter, so give it a dummy name.
Also fixes a test assertion that assumed forward slash path separators.

Fix path issues on Windows.

---

.github/workflows/build-test.yaml
.gitignore
Cargo.lock
Cargo.toml
README.md
pyproject.toml
src/lib.rs
src/query/mod.rs
src/query/python.rs
src/query/query_eval.rs
src/query/query_parse.rs
src/query/query_types.rs
src/query/test_utils_query.rs
tests/python/conftest.py
tests/python/test_parse.py
tests/python/test_pattern_match.py

The existing query parser is exposed as a new Python package called `outpack_query_parser`. The package contains a single function, `parse_query` which turns a string into an AST.
The AST is represented with Python objects, and can be printed and pattern matched on.

Add python bindings for the query parser.

---

schema/server/list.json
src/metadata.rs
tests/test_api.rs

This PR alters data returned from enpoint `/packit/metadata?<known_since>` used by packit... This adds time field and removes custom field.

MRC 4770 - Add time field and remove custom from packit endpoint

---

.github/workflows/build-test.yaml
.github/workflows/python.yaml
Cargo.toml
pyproject.toml

This will allow users to install and import the Python bindings without needing to install a Rust toolchain.
The wheels should work on most mainstream platforms and architecture. We can add more if it turns out there's a gap somewhere. Additionally it uses abi3 wheels, which will work on any Python version >= 3.8, see https://pyo3.rs/v0.20.0/building_and_distribution#py_limited_apiabi3
The wheels are built unconditionally on every commit to master and PR commit. Additionally, whenever a tag is created the source package and wheels are pushed to PyPI.
I used TestPyPi to check the publish process and it seems to work fine. Of course there's a small chance this will not work on the first release attempt and need a bit more iteration later on.

mrc-4786: Build Python wheels in CI.

---

README.md

Basically just a log of the steps I took for 0.3.0, so we can repeat them easily in the future.

Add releasing documentation to the README.

---

Cargo.lock
Cargo.toml
src/api.rs
src/store.rs
tests/test_api.rs

The endpoint will allow Prometheus to scrape metrics from the service. For now, only basic information about request count and timing is exposed, through the `rocket_prometheus` crate. The same crate provides the implementation of the endpoint too.
The crate looks for metrics in a global registry, which will allow us to add some of our own metrics in the future.
The response of the `/metrics` is formatted according to Prometheus' [text-based exposition format](https://prometheus.io/docs/instrumenting/exposition_formats/)
Below is an example of what the endpoint looks like, after just one request to the `/` endpoint:
```
rocket_http_requests_duration_seconds_bucket{endpoint="/",method="GET",status="200",le="0.005"} 1
rocket_http_requests_duration_seconds_bucket{endpoint="/",method="GET",sta …
```

mrc-5002: Add a /metrics endpoint with basic metrics.

---

Cargo.lock
Cargo.toml
src/api.rs
src/lib.rs
src/metadata.rs
src/metrics.rs
src/store.rs
src/test_utils.rs

These track the number of unpacked packets, the number of metadata files, the number of files in the store and the total byte size of those.
Here's an example of the generated metrics, after having pushed one packet to the server:
```
outpack_server_file_size_bytes_total 452
outpack_server_files_total 2
outpack_server_metadata_total 1
outpack_server_packets_total 1
```
Some other changes along the way:
- Added an API to generate packet metadata, for tests.
- `get_ids` used to take an `Option<bool>`, where `Some(false)` and `false` had the same semantics. Replaced with a plain `bool`.
- `put_file`'s argument is generalized to accept either a `TempFile` or a byte slice, making test code a bit more concise.
- Some tests were flaky because of a Rocket bug. I had fixed it upstream a while ago, …

mrc-5011: Add gauges to monitor the size of the repository.

---

src/api.rs
src/metadata.rs

Rocket was throwing warnings at runtime about it being inefficient.
See https://api.rocket.rs/v0.5/src/rocket/request/from_param.rs.html#201-205.

Replace uses of `String` with `&str` in API.

---

src/api.rs
src/bin/outpack/args.rs
src/config.rs
src/hash.rs
src/index.rs
src/init.rs
src/location.rs
src/metadata.rs
src/metrics.rs
src/query/mod.rs
src/query/query_eval.rs
src/query/query_format.rs
src/store.rs
src/test_utils.rs
tests/test_api.rs
tests/test_query.rs

Using strings requires verbose conversions to and from path types anytime we want to use path operations (ie. `join()` is the vast majority of cases).
Using the path types consistently everywhere means we never have to worry about conversions. We get a `PathBuf` straight from our command-line arguments and stick to it. The only exception is tests, which frequently use a string literal to point to the example repo. These string literals now need to be replaced with `Path::new(...)`.
This is a fairly large but mostly mechanical change. `String` is replaced by `PathBuf` and `&str` is replaced by `&Path`. Conversion code here and there gets removed.

Use Path/PathBuf for the repository root.

---

Cargo.lock
Cargo.toml
Dockerfile
Rocket.toml
src/api.rs
src/bin/outpack/main.rs
src/lib.rs
src/metrics.rs
src/outpack_file.rs
src/responses.rs
src/store.rs
src/upload.rs
tests/test_api.rs

Axum gives us more control over the flow of requests and allows us to use all the tower ecosystem, which has a lot of nice middlewares.
The first immediate benefit we get is better logging using the tracing ecosystem and support for a request ID. Clients can send a `x-request-id` header, which will be included in all log messages printed by the request. If no ID is provided one is generated randomly by the server. The ID, generated or provided by the client, is also included in the response.
Most of our business code and endpoints are untouched, since Rocket and Axum use fairly similar paradigms anyway. Most of the changes are in auxilary code, such as testing, metrics and response formatting.

Replace Rocket with Axum.

---

README.md
README.python.md
pyproject.toml

By default Hatch automatically includes the README.md file at the root
of the project as the Python package's description, which shows up when
looking at the package on PyPI. Since the README mostly contains
information about the server this could lead to confusion, with users
trying to start a server when what they really wanted was to be
redirected to the main outpack-py package.
This adds a minimal README with the Python specific information, and a
link to the main package. The new file is referenced from
`pyproject.toml`, ensuring this is what gets used as the description
rather than the default one.

Add a custom Python README.

---

README.md
schema/server/branch.json
schema/server/branches.json
src/api.rs
src/git.rs
start-with-wait
tests/test_api.rs

This should add a get endpoint `/git/branches` to get information about the available branches. Main changes include:
* added git fetch and git branches endpoints to the README
* added `git_list_branches` function
* changed `git/fetch` endpoint to a get instead of a post, made more sense to me
* had to add `git config --global --add safe.directory /outpack` to `start-with-wait` because git was complaining about not being the owner of the repository
To test this manually, you can go to `/outpack` in the docker container and make some git branches or you can just mount a git repo into `/outpack` and then `curl localhost:8000/git/branches`
Note the original ticket also suggested having a boolean to show if the branch had unmerged commits or not, i could not find a super easy way to do this …

mrc-4973 Add list branches endpoint

---

Cargo.lock
Cargo.toml
src/api.rs
src/hash.rs
src/metadata.rs
src/metrics.rs
src/store.rs
src/upload.rs
tests/test_api.rs

Previously files were being hashed by loading them in memory entirely first, then hashing the resulting buffer. When uploading large files, this puts a lot of memory pressure on the server.
Thankfully the hash types provide `io::Write`, meaning implementing a streaming hash is as straightforward as using `io::copy` from the input into them.
A few adjecent changes, mostly about wrapping some code behind a `spawn_blocking` call; a lot of our implementation is synchronous, and calling it directly from the main thread could cause it to block. The biggest offenders were the aforementioned hashing, and git operations.

Add a streaming hash implementation.

---

Cargo.lock
Cargo.toml
build.rs
src/api.rs
src/metrics.rs
test-utils/Cargo.toml

This describes the server's version and build environment. For now it only contains the version number (as specified in the `Cargo.toml`), the git revision and the Rust version used in the build.
The versions are listed as labels, and the metric has a value of 1. This follows the convention that is widespread in the Prometheus ecosystem.
This is what the resulting metric might look like:
```
outpack_server_build_info{revision="dd6b97db1f52ece5ea4b635ec43655d005ad7627",rustc="1.78.0",version="0.3.0"} 1
```

Add an outpack_server_build_info metric.

---

README.md
schema/server/list.json
src/metadata.rs
tests/test_api.rs

This brings the implementation of the API to be more in line with the spec as it was in the README: namely, the /packit/metadata endpoint will now pass on the 'custom' property as part of the response. (The README also didn't show that the 'time' property was being returned.)

Add custom metadata to /packit/metadata endpoint

---

.github/workflows/python.yaml
src/metadata.rs
src/utils.rs

GitHub has decomissioned upload-artifact v3 and is forcing everyone to use v4. These work in similar ways, except v4 doesn't allow multiple jobs to push to the same artifact name anymore. We need to use distinct names for each OS/architecture pair, and have the call to download-artifact pull and merge them all. This is based on the [cibuildwheel documentation][cibuildwheel].
A couple of clippy fixes along the way.
[cibuildwheel]: https://cibuildwheel.pypa.io/en/stable/deliver-to-pypi/

Fix the outpack_server build.

---

Cargo.toml

Failing to install for me with:
```
cargo install --git https://github.com/mrc-ide/outpack_server outpack
```
with error
```
error[E0432]: unresolved import `tokio::io::AsyncWriteExt`
--> src/upload.rs:10:5
|
10  | use tokio::io::AsyncWriteExt;
|     ^^^^^^^^^^^^^^^^^^^^^^^^ no `AsyncWriteExt` in `io`
|
note: found an item that was configured out
--> /home/rich/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/io/mod.rs:277:159
|
277 | ... AsyncBufReadExt, AsyncReadExt, AsyncSeekExt, AsyncWriteExt,
|                                                  ^^^^^^^^^^^^^
note: the item is gated behind the `io-util` feature
--> /home/rich/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tokio-1.44.2/src/io/mod.rs:268:1
|
268 | / cfg_io_util! {
269 | |     mod split;
270 | | …
```

Add io-util feature

---

Cargo.toml
src/config.rs
tests/bad-example/.outpack/config.json
tests/example/.outpack/config.json

We need a location entry for orderly2 to be able to interact with the outpack archive, at least for things like migrating data.  This PR adds the "local" location, which orderly treats specially (to the point where it cannot add it).
Metadata on initialisation, after this PR:
```
{
"core": {
"hash_algorithm": "sha256",
"path_archive": null,
"use_file_store": true,
"require_complete_tree": false
},
"location": [
{
"name": "local",
"type": "local",
"args": {}
}
]
}
```
Currently the `location` section is the empty list.

Add additional metadata
